#application: blog
#version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /www
  static_dir: www
  application_readable: true

- url: /www/content/img
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: blog.app  

libraries:
- name: jinja2
  version: latest